# Normalization Data and Principle Component Analysis

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('PastHires.csv')

In [4]:
df

,Years Experience,Employed?,Previous employers,Level of Education,Top-tier school,Interned,Hired
0,10,Y,4,BS,N,N,Y
1,0,N,0,BS,Y,Y,Y
2,7,N,6,BS,N,N,N
3,2,Y,1,MS,Y,N,Y
4,20,N,2,PhD,Y,N,N
5,0,N,0,PhD,Y,Y,Y
6,5,Y,2,MS,N,Y,Y
7,3,N,1,BS,N,Y,Y
8,15,Y,5,BS,N,N,Y
9,0,N,0,BS,N,N,N
10,1,N,1,PhD,Y,N,N
11,4,Y,1,BS,N,Y,Y
12,0,N,0,PhD,Y,N,Y

In [5]:
# Employed tablosunda ki Y=1 N=0 , Level of Education tablosundaki verileri de 1-2-3 olarak değiştireceğiz

In [7]:
df['Employed?']=df['Employed?'].map({'Y' : 1 , 'N' : 0})

In [8]:
df

,Years Experience,Employed?,Previous employers,Level of Education,Top-tier school,Interned,Hired
0,10,1,4,BS,N,N,Y
1,0,0,0,BS,Y,Y,Y
2,7,0,6,BS,N,N,N
3,2,1,1,MS,Y,N,Y
4,20,0,2,PhD,Y,N,N
5,0,0,0,PhD,Y,Y,Y
6,5,1,2,MS,N,Y,Y
7,3,0,1,BS,N,Y,Y
8,15,1,5,BS,N,N,Y
9,0,0,0,BS,N,N,N
10,1,0,1,PhD,Y,N,N
11,4,1,1,BS,N,Y,Y
12,0,0,0,PhD,Y,N,Y

In [9]:
# tek satırda değiştirmek istediğimiz verileri değiştirme komutu

In [12]:
df = df.replace({'Y' : 1 , 'N' : 0, 'BS' : 1 , 'MS' : 2 , 'PhD' : 3})

/var/folders/bd/ynlx2tbx6hldfs4b77fg6sm40000gn/T/ipykernel_5413/1337112778.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({'Y' : 1 , 'N' : 0, 'BS' : 1 , 'MS' : 2 , 'PhD' : 3})

In [13]:
df

,Years Experience,Employed?,Previous employers,Level of Education,Top-tier school,Interned,Hired
0,10,1,4,1,0,0,1
1,0,0,0,1,1,1,1
2,7,0,6,1,0,0,0
3,2,1,1,2,1,0,1
4,20,0,2,3,1,0,0
5,0,0,0,3,1,1,1
6,5,1,2,2,0,1,1
7,3,0,1,1,0,1,1
8,15,1,5,1,0,0,1
9,0,0,0,1,0,0,0
10,1,0,1,3,1,0,0
11,4,1,1,1,0,1,1
12,0,0,0,3,1,0,1

In [16]:
# datayı normalize edeceğiz (belirli bir değer aralığına indirgiyoruz) her veriden min değeri çıkart / max - min değer

# Normalizing Data

<img src="https://cdn.educba.com/academy/wp-content/uploads/2019/05/Normalization-Formula.jpg" width=300>

In [15]:
from sklearn.preprocessing import normalize, scale

In [17]:
yenidf = normalize(df)

In [18]:
pd.DataFrame (yenidf)

           0         1         2         3         4         5         6
0   0.916698  0.091670  0.366679  0.091670  0.000000  0.000000  0.091670
1   0.000000  0.000000  0.000000  0.500000  0.500000  0.500000  0.500000
2   0.754829  0.000000  0.646997  0.107833  0.000000  0.000000  0.000000
3   0.577350  0.288675  0.288675  0.577350  0.288675  0.000000  0.288675
4   0.982946  0.000000  0.098295  0.147442  0.049147  0.000000  0.000000
5   0.000000  0.000000  0.000000  0.866025  0.288675  0.288675  0.288675
6   0.833333  0.166667  0.333333  0.333333  0.000000  0.166667  0.166667
7   0.832050  0.000000  0.277350  0.277350  0.000000  0.277350  0.277350
8   0.943042  0.062869  0.314347  0.062869  0.000000  0.000000  0.062869
9   0.000000  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000
10  0.288675  0.000000  0.288675  0.866025  0.288675  0.000000  0.000000
11  0.872872  0.218218  0.218218  0.218218  0.000000  0.218218  0.218218
12  0.000000  0.000000  0.000000  0.904534  0.301511  0.000000  0.301511

In [19]:
# normalize edildiğinde bütün veriler aynı tipe döndü ve veri olarak da küçüldüğü için işlemesi daha kolay hale geldi

In [21]:
scaled_data=scale(df)

In [23]:
scaled_data # ortalamayı -1 ile 1 arasına düşürdü

array([[ 0.7944824 ,  1.26491106,  1.15722598, -0.86386843, -0.9258201 ,
        -0.79056942,  0.66666667],
       [-0.84492573, -0.79056942, -0.91779992, -0.86386843,  1.08012345,
         1.26491106,  0.66666667],
       [ 0.30265996, -0.79056942,  2.19473893, -0.86386843, -0.9258201 ,
        -0.79056942, -1.5       ],
       [-0.5170441 ,  1.26491106, -0.39904344,  0.25916053,  1.08012345,
        -0.79056942,  0.66666667],
       [ 2.43389054, -0.79056942,  0.11971303,  1.38218948,  1.08012345,
        -0.79056942, -1.5       ],
       [-0.84492573, -0.79056942, -0.91779992,  1.38218948,  1.08012345,
         1.26491106,  0.66666667],
       [-0.02522166,  1.26491106,  0.11971303,  0.25916053, -0.9258201 ,
         1.26491106,  0.66666667],
       [-0.35310329, -0.79056942, -0.39904344, -0.86386843, -0.9258201 ,
         1.26491106,  0.66666667],
       [ 1.61418647,  1.26491106,  1.67598246, -0.86386843, -0.9258201 ,
        -0.79056942,  0.66666667],
       [-0.84492573, -0.79056942, -0.91779992, -0.86386843, -0.9258201 ,
        -0.79056942, -1.5       ],
       [-0.68098492, -0.79056942, -0.39904344,  1.38218948,  1.08012345,
        -0.79056942, -1.5       ],
       [-0.18916248,  1.26491106, -0.39904344, -0.86386843, -0.9258201 ,
         1.26491106,  0.66666667],
       [-0.84492573, -0.79056942, -0.91779992,  1.38218948,  1.08012345,
        -0.79056942,  0.66666667]])

In [24]:
df.shape # kaç satır stün

(13, 7)

In [25]:
from sklearn.decomposition import PCA

In [26]:
pca=PCA(3) # datayı 3 stuna indirgeme

In [28]:
data2=pca.fit_transform(df)

In [29]:
pd.DataFrame(data2)

            0         1         2
0    5.238052  1.443926 -0.332178
1   -5.439797 -0.395424 -0.860868
2    2.724357  3.691323  1.170105
3   -3.234185 -0.171342  0.178791
4   14.538013 -3.360925  0.374655
5   -5.457536 -1.152829  0.599512
6   -0.104176  0.275826 -0.288435
7   -2.280997  0.089549 -1.011542
8   10.331511  1.321587 -0.344215
9   -5.377586 -0.157493 -0.569935
10  -4.226027 -0.449023  1.489810
11  -1.282886 -0.020150 -1.321764
12  -5.428744 -1.115024  0.916064

In [30]:
df

,Years Experience,Employed?,Previous employers,Level of Education,Top-tier school,Interned,Hired
0,10,1,4,1,0,0,1
1,0,0,0,1,1,1,1
2,7,0,6,1,0,0,0
3,2,1,1,2,1,0,1
4,20,0,2,3,1,0,0
5,0,0,0,3,1,1,1
6,5,1,2,2,0,1,1
7,3,0,1,1,0,1,1
8,15,1,5,1,0,0,1
9,0,0,0,1,0,0,0
10,1,0,1,3,1,0,0
11,4,1,1,1,0,1,1
12,0,0,0,3,1,0,1

In [31]:
# yukarıda ki iki data da bilgisayar için aynı

In [32]:
# PCA yaptık, iz düşümünü aldık datanın